export default [
	"Joshua Sandoval",
	"Linus Torvalds",
	"James Gosling",
	"Dennis Ritchie",
	"Bill Gates",
	"Mark Zuckerberg",
	"Ken Thompson",
	"Guido van Rossum",
	"Brian Kernighan",
	"Tim Berners-Lee",
	"Anders Hejlsberg",
	"Bjarne Stroustrup",
	"Steve Wozniak",
	"Donald Knuth",
	"Richard Stallman",
	"John Carmack",
	"Brendan Eich",
	"Jack Dorsey",
	"Sergey Brin",
	"Eric S. Raymond",
	"John Resig",
	"Jon Skeet",
	"Fabrice Bellard",
	"Larry Page"
]